version: '1.0'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - /home/mongo:/data/db
    networks:
      - webapp-network
  app:
    image: egg-blog-be
    command: node start
    depends_on:
      - database
    ports:
      - 7001:7001
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge